import tkinter as tk
from tkinter import *
from tkinter import  messagebox
def hello1():
 msg = messagebox.showinfo( "Confirmation","Submitted Sucessfully!")
def hello11():
 msg = messagebox.showinfo( "Confirmation","Fields have been Reset!")
def test():
 if v1.get()==1:
  v2.set(0)
  v3.set(0)
  v4.set(0)
  v5.set(0)
 if v2.get()==1:
  v1.set(0)
  v3.set(0)
  v4.set(0)
  v5.set(0)
 if v3.get()==1:
  v2.set(0)
  v1.set(0)
  v4.set(0)
  v5.set(0)
 if v4.get()==1:
  v2.set(0)
  v3.set(0)
  v1.set(0)
  v5.set(0)
 if v5.get()==1:
  v2.set(0)
  v3.set(0)
  v4.set(0)
  v1.set(0)
root=tk.Tk()
root.title('STUDENT REGISTRATION FORM')
root.geometry('800x500')
root.configure(bg='slateblue1')
l1=tk.Label(root,text="FIRST NAME",fg='white',bg='slateblue1')
l1.grid(sticky='w',row=0)
l1_1=tk.Label(root,text="(max 30 characters a-z and A-Z)",fg='white',bg='slateblue1')
l1_1.grid(row=0,column=2)
t1=tk.Entry(root)
t1.grid(row=0,column=1)
l2=tk.Label(root,text="LAST NAME",fg='white',bg='slateblue1')
l2.grid(sticky='w',row=1)
l2_1=tk.Label(root,text="(max 30 characters a-z and A-Z)",fg='white',bg='slateblue1')
l2_1.grid(row=1,column=2)
t2=tk.Entry(root)
t2.grid(row=1,column=1)
l8=tk.Label(root,text="DATE OF BIRTH",fg='white',bg='slateblue1')
l8.grid(sticky='w',row=2)
variabled= StringVar(root)
variabled.set("Day:")
d = OptionMenu(root, variabled, "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11","12","13","14","15","16","17","18","19","20","21","22","23","24"
               "25", "26", "27", "28", "29", "30","31")
d.grid(sticky='w',row=2,column=1)
d.config(fg='white',bg='slateblue1')
variablem= StringVar(root)
variablem.set("Month:")
m = OptionMenu(root, variablem, "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov",
               "Dec")
m.grid(sticky='w',row=2,column=2)
m.config(fg='white',bg='slateblue1')
variabley= StringVar(root)
variabley.set("Year:")
y = OptionMenu(root, variabley, "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960",
               "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973",
               "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986",
               "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999",
               "2000", "2001", "2002", "2003", "2004", "2005")
y.config(fg='white',bg='slateblue1')
y.grid(sticky='w',row=2,column=3,)
l3=tk.Label(root,text="EMAIL ID",fg='white',bg='slateblue1')
l3.grid(sticky='w',row=3)
t3=tk.Entry(root)
t3.grid(row=3,column=1)
l4=tk.Label(root,text="MOBILE NUMBER",fg='white',bg='slateblue1')
l4.grid(sticky='w',row=4)
l4_1=tk.Label(root,text="(10 digit number)",fg='white',bg='slateblue1')
l4_1.grid(sticky='w',row=4,column=2)
t4=tk.Entry(root)
t4.grid(row=4,column=1)
lg=tk.Label(root,text="GENDER",fg='white',bg='slateblue1')
lg.grid(sticky='w',row=5)
radio11=IntVar()
radio21=IntVar()
rb11=Radiobutton(root,text='Male',variable=radio11,fg='black',bg='slateblue1',value=1)
rb11.grid(sticky='w',row=5,column=1)
rb21=Radiobutton(root,text='Female',variable=radio21,fg='black',bg='slateblue1',value=2)
rb21.grid(sticky='w',row=5,column=2)
la=tk.Label(root,text='ADDRESS',fg='white',bg='slateblue1')
la.grid(sticky='w',row=6)
ta=tk.Text(root,width=15,height=3)
ta.grid(sticky='w',row=6,column=1)
l5=tk.Label(root,text="CITY",fg='white',bg='slateblue1')
l5.grid(sticky='w',row=7)
t5=tk.Entry(root)
t5.grid(row=7,column=1)
l5_1=tk.Label(root,text="(max 30 characters a-z and A-Z)",fg='white',bg='slateblue1')
l5_1.grid(row=7,column=2)
l6=tk.Label(root,text="PIN CODE",fg='white',bg='slateblue1')
l6.grid(sticky='w',row=8)
t6=tk.Entry(root)
t6.grid(row=8,column=1)
l6_1=tk.Label(root,text="(6 digit number)",fg='white',bg='slateblue1')
l6_1.grid(sticky='w',row=8,column=2)
l7=tk.Label(root,text="STATE",fg='white',bg='slateblue1')
l7.grid(sticky='w',row=9)
t7=tk.Entry(root)
t7.grid(row=9,column=1)
l7_1=tk.Label(root,text="(max 30 characters a-z and A-Z)",fg='white',bg='slateblue1')
l7_1.grid(row=9,column=2)
v=tk.StringVar()
v.set("India")
l8=tk.Label(root,text="COUNTRY",fg='white',bg='slateblue1')
l8.grid(sticky='w',row=10)
t8=tk.Entry(root,textvariable=v)
t8.grid(row=10,column=1)
l9=tk.Label(root,text="HOBBIES",fg='white',bg='slateblue1')
l9.grid(sticky='w',row=11)
v1=IntVar()
v2=IntVar()
v3=IntVar()
v4=IntVar()
v5=IntVar()
cb1=Checkbutton(root,text='Drawing', variable=v1,onvalue=1, offvalue=0, command=test,fg='black',bg='slateblue1')
cb1.grid(sticky='w',row=11,column=1)
cb2=Checkbutton(root,text='Singing', variable=v2,onvalue=1, offvalue=0,command=test,fg='black',bg='slateblue1')
cb2.grid(sticky='w',row=11,column=2)
cb3=Checkbutton(root,text='Dancing', variable=v3,onvalue=1, offvalue=0,command=test,fg='black',bg='slateblue1')
cb3.grid(sticky='w',row=11,column=3)
cb4=Checkbutton(root,text='Sketching', variable=v4,onvalue=1, offvalue=0,command=test,fg='black',bg='slateblue1')
cb4.grid(sticky='w',row=11,column=4)
cb5=Checkbutton(root,text='Other', variable=v5,onvalue=1, offvalue=0,command=test,fg='black',bg='slateblue1')
cb5.grid(sticky='w',row=12,column=1)
cb5w=tk.Entry(root)
cb5w.grid(sticky='w',row=12,column=2)
l10=tk.Label(root,text="QUALIFICATION",fg='white',bg='slateblue1')
l10.grid(sticky='w',row=13)
l11=tk.Label(root,text="S.No.",fg='white',bg='slateblue1')
l11.grid(sticky='w',row=13,column=1)
l12=tk.Label(root,text="Examination",fg='white',bg='slateblue1')
l12.grid(sticky='w',row=13,column=2)
l13=tk.Label(root,text="Board",fg='white',bg='slateblue1')
l13.grid(sticky='w',row=13,column=3)
l14=tk.Label(root,text="Percentage",fg='white',bg='slateblue1')
l14.grid(sticky='w',row=13,column=4)
l15=tk.Label(root,text="Year Of Passing",fg='white',bg='slateblue1')
l15.grid(sticky='w',row=13,column=5)
l16=tk.Label(root,text="1",fg='white',bg='slateblue1')
l16.grid(sticky='w',row=14,column=1)
l17=tk.Label(root,text="2",fg='white',bg='slateblue1')
l17.grid(sticky='w',row=15,column=1)
l18=tk.Label(root,text="3",fg='white',bg='slateblue1')
l18.grid(sticky='w',row=16,column=1)
l19=tk.Label(root,text="4",fg='white',bg='slateblue1')
l19.grid(sticky='w',row=17,column=1)
l20=tk.Label(root,text="Class X",fg='white',bg='slateblue1')
l20.grid(sticky='w',row=14,column=2)
l21=tk.Label(root,text="Class XII",fg='white',bg='slateblue1')
l21.grid(sticky='w',row=15,column=2)
l22=tk.Label(root,text="Graduation",fg='white',bg='slateblue1')
l22.grid(sticky='w',row=16,column=2)
l23=tk.Label(root,text="Masters",fg='white',bg='slateblue1')
l23.grid(sticky='w',row=17,column=2)
t9=tk.Entry(root)
t9.grid(row=14,column=3)
t10=tk.Entry(root)
t10.grid(row=15,column=3)
t11=tk.Entry(root)
t11.grid(row=16,column=3)
t12=tk.Entry(root)
t12.grid(row=17,column=3)
t13=tk.Entry(root)
t13.grid(row=14,column=4)
t14=tk.Entry(root)
t14.grid(row=15,column=4)
t15=tk.Entry(root)
t15.grid(row=16,column=4)
t16=tk.Entry(root)
t16.grid(row=17,column=4)
t17=tk.Entry(root)
t17.grid(row=17,column=5)
t18=tk.Entry(root)
t18.grid(row=14,column=5)
t19=tk.Entry(root)
t19.grid(row=15,column=5)
t20=tk.Entry(root)
t20.grid(row=16,column=5)
l24=tk.Label(root,text="(10 char max)",fg='white',bg='slateblue1')
l24.grid(row=18,column=3)
l25=tk.Label(root,text="(upto 2 decimal)",fg='white',bg='slateblue1')
l25.grid(row=18,column=4)
l26=tk.Label(root,text="COURSES APPLIED FOR",fg='white',bg='slateblue1')
l26.grid(row=19)
radio=IntVar()
rb1=Radiobutton(root,text='BCA', variable=radio,fg='black',bg='slateblue1',value=3)
rb1.grid(sticky='w',row=19,column=1)
radio1=IntVar()
rb2=Radiobutton(root,text='B.com', variable=radio1,fg='black',bg='slateblue1',value=3)
rb2.grid(sticky='w',row=19,column=2)
radio2=IntVar()
rb3=Radiobutton(root,text='B.Sc', variable=radio2,fg='black',bg='slateblue1',value=5)
rb3.grid(sticky='w',row=19,column=3)
radio3=IntVar()
rb4=Radiobutton(root,text='B.A', variable=radio3,fg='black',bg='slateblue1',value=6)
rb4.grid(sticky='w',row=19,column=4)
b1=tk.Button(root, text='Sumbit',fg='black',bg='white',command=hello1)
b1.grid(sticky='s',row=20,column=1)
b2=tk.Button(root, text='Reset',fg='black',bg='white',command=hello11)
b2.grid(sticky='s',row=20,column=2)
root.mainloop()