import tkinter as tk
from tkinter import *
from tkinter import  messagebox
def hello1():
 msg = messagebox.showinfo( "Confirmation","Submitted Sucessfully")
root=tk.Tk()
root.title('Bookstore Management System')
root.geometry('550x400')
l1=tk.Label(root,text="Title")
l1.grid(sticky='w',row=0,column=0)
t1=tk.Entry(root)
t1.grid(sticky='w',row=0,column=1)
l2=tk.Label(root,text="Author")
l2.grid(sticky='w',row=0,column=2)
t2=tk.Entry(root)
t2.grid(sticky='w',row=0,column=3)
l11=tk.Label(root,text="Year")
l11.grid(sticky='w',row=1,column=0)
t11=tk.Entry(root)
t11.grid(sticky='w',row=1,column=1)
l12=tk.Label(root,text="ISBN")
l12.grid(sticky='w',row=1,column=2)
t12=tk.Entry(root)
t12.grid(sticky='w',row=1,column=3)
l4 = tk.Label(root,text='ID--Title--Author--Year--ISBN')
l4.grid(sticky='w',row=2)
t4 = tk.Text(root,height=8,width=25)
t4.grid(sticky='w',row=3,column=0,columnspan=10)
b1=tk.Button(root, text='Update/Delete',command=hello1)
b1.grid(sticky='s',row=2,column=2)
b2=tk.Button(root, text='Close',command=root.destroy)
b2.grid(sticky='s',row=3,column=2)
root.mainloop()