import tkinter as tk
from tkinter import *
from tkinter import  messagebox
def hello1():
 msg = messagebox.showinfo( "Confirmation","Applied with given details Sucessfully!")
def hello11():
  msg = messagebox.showinfo("Choose File", "Upload Resume")
root=tk.Tk()
root.title('Job Application')
root.geometry('750x600')
l01=tk.Label(root,text='Personal Details',fg='maroon',font=("Times New Roman", 14))
l01.grid(sticky='w',row=0)
l1=tk.Label(root,text="Name")
l1.grid(sticky='w',row=1)
t1=tk.Entry(root)
t1.grid(sticky='w',row=1,column=1)
t2=tk.Entry(root)
t2.grid(sticky='w',row=1,column=2)
l1_1=tk.Label(root,text="First Name",font=("Times New Roman", 7))
l1_1.grid(sticky='w',row=2,column=1)
l2=tk.Label(root,text="Last Name",font=("Times New Roman", 7))
l2.grid(sticky='w',row=2,column=2)
l8=tk.Label(root,text="Email")
l8.grid(sticky='w',row=3)
var=StringVar()
var.set("user@example.com")
t3=tk.Entry(root,textvariable=var)
t3.grid(sticky='w',row=3,column=1)
l3=tk.Label(root,text="Education")
l3.grid(sticky='w',row=4)
variabledu= StringVar(root)
variabledu.set("Please Choose")
edu = OptionMenu(root, variabledu, "X","XII","Graduate","Masters","PhD")
edu.grid(sticky='w',row=4,column=1)
l4=tk.Label(root,text="Resume")
l4.grid(sticky='w',row=5)
br=tk.Button(root,text='Choose File',command=hello11)
br.grid(sticky='w',row=5,column=1)
tv1=StringVar()
tv1.set("No File Chosen")
l4_1=tk.Entry(root,textvariable=tv1)
l4_1.grid(sticky='w',row=5,column=2)
lg=tk.Label(root,text="Address")
lg.grid(sticky='w',row=6)
a1=StringVar()
a1.set("Address 1")
a2=StringVar()
a2.set("Address 2")
tg1=tk.Entry(root,width=30,textvariable=a1)
tg1.grid(sticky='w',row=6,column=1)
tg2=tk.Entry(root,width=30,textvariable=a2)
tg2.grid(sticky='w',row=7,column=1)
variablec= StringVar(root)
variablec.set("Select A Country")
c= OptionMenu(root, variablec, "IND", "USA", "JAP", "UK", "NED", "SIN", "PAK", "ISR", "AUS", "BAH", "THA",
               "OTH")
c.grid(sticky='w',row=8,column=1)
c.config(width=20)
l6=StringVar()
l6.set("City")
t6=tk.Entry(root,textvariable=l6)
t6.grid(sticky='w',row=9,column=1)
l6_1=StringVar()
l6_1.set("State")
t6_2=tk.Entry(root,textvariable=l6_1,width=5)
t6_2.grid(sticky='w',row=9,column=2)
l7=StringVar()
l7.set("Zip Code")
t7=tk.Entry(root,textvariable=l7,width=10)
t7.grid(sticky='w',row=9,column=3)
l7_1=tk.Label(root,text="Phone Number")
l7_1.grid(sticky='w',row=10)
tph1=tk.Entry(root,width=5)
tph1.grid(sticky='w',row=10,column=1)
tph2=tk.Entry(root)
tph2.grid(sticky='w',row=10,column=2)
l8=tk.Label(root,text="What are your hobbies?")
l8.grid(sticky='w',row=11)
t8=tk.Entry(root,width=40)
t8.grid(sticky='w',row=12)
l9=tk.Label(root,text="Previous/Current Employment Details",fg='maroon',font=("Times New Roman", 14))
l9.grid(sticky='w',row=13)
l10=tk.Label(root,text="Company Name")
l10.grid(sticky='w',row=14)
cb5w=tk.Entry(root,width=30)
cb5w.grid(sticky='w',row=14,column=1)
l11=tk.Label(root,text="Job Title")
l11.grid(sticky='w',row=15)
t9=tk.Entry(root,width=30)
t9.grid(sticky='w',row=15,column=1)
l12=tk.Label(root,text="How long were you there?")
l12.grid(sticky='w',row=16)
t10=tk.Entry(root,width=30)
t10.grid(sticky='w',row=16,column=1)
l13=tk.Label(root,text="Reference #1",fg='maroon',font=("Times New Roman", 14))
l13.grid(sticky='w',row=17)
l14=tk.Label(root,text="Name")
l14.grid(sticky='w',row=18)
t11=tk.Entry(root,width=30)
t11.grid(sticky='w',row=18,column=1)
l15=tk.Label(root,text="Phone")
l15.grid(sticky='w',row=19)
t13=tk.Entry(root,width=30)
t13.grid(sticky='w',row=19,column=1)
l16=tk.Label(root,text="Reference #2",fg='maroon',font=("Times New Roman", 14))
l16.grid(sticky='w',row=20)
l17=tk.Label(root,text="Name")
l17.grid(sticky='w',row=21)
l18=tk.Label(root,text="Phone")
l18.grid(sticky='w',row=22)
t12=tk.Entry(root,width=30)
t12.grid(sticky='w',row=21,column=1)
t14=tk.Entry(root,width=30)
t14.grid(sticky='w',row=22,column=1)
b1=tk.Button(root, text='Apply',fg='white',bg='maroon',command=hello1)
b1.grid(sticky='s',row=23,column=1)
root.mainloop()