import tkinter as tk
from tkinter import *
def f():
 if (vloc21.get() == 1):
  vloc22.set(0)
 elif (vloc22.get() == 1):
  vloc21.set(0)
def test2():
 if (vloc1.get() == 1):
  vloc2.set(0)
  vloc3.set(0)
 elif (vloc2.get() == 1):
  vloc1.set(0)
  vloc3.set(0)
 elif(vloc3.get() == 1):
  vloc1.set(0)
  vloc2.set(0)
def test1():
 if v4.get()==1:
  v5.set(0)
  v6.set(0)
  v7.set(0)
  v8.set(0)
  v9.set(0)
  v10.set(0)
  v11.set(0)
  v12.set(0)
  v13.set(0)
  v14.set(0)
 elif v5.get()==1:
  v4.set(0)
  v6.set(0)
  v7.set(0)
  v8.set(0)
  v9.set(0)
  v10.set(0)
  v11.set(0)
  v12.set(0)
  v13.set(0)
  v14.set(0)
 elif v6.get()==1:
  v5.set(0)
  v4.set(0)
  v7.set(0)
  v8.set(0)
  v9.set(0)
  v10.set(0)
  v11.set(0)
  v12.set(0)
  v13.set(0)
  v14.set(0)
 elif v7.get()==1:
  v5.set(0)
  v6.set(0)
  v4.set(0)
  v8.set(0)
  v9.set(0)
  v10.set(0)
  v11.set(0)
  v12.set(0)
  v13.set(0)
  v14.set(0)
 elif v8.get()==1:
  v5.set(0)
  v6.set(0)
  v7.set(0)
  v4.set(0)
  v9.set(0)
  v10.set(0)
  v11.set(0)
  v12.set(0)
  v13.set(0)
  v14.set(0)
 elif v9.get()==1:
  v5.set(0)
  v6.set(0)
  v7.set(0)
  v4.set(0)
  v8.set(0)
  v10.set(0)
  v11.set(0)
  v12.set(0)
  v13.set(0)
  v14.set(0)
 elif v10.get()==1:
  v5.set(0)
  v6.set(0)
  v7.set(0)
  v4.set(0)
  v9.set(0)
  v8.set(0)
  v11.set(0)
  v12.set(0)
  v13.set(0)
  v14.set(0)
 elif v11.get()==1:
  v5.set(0)
  v6.set(0)
  v7.set(0)
  v4.set(0)
  v9.set(0)
  v10.set(0)
  v8.set(0)
  v12.set(0)
  v13.set(0)
  v14.set(0)
 elif v12.get()==1:
  v5.set(0)
  v6.set(0)
  v7.set(0)
  v4.set(0)
  v9.set(0)
  v10.set(0)
  v11.set(0)
  v8.set(0)
  v13.set(0)
  v14.set(0)
 elif v13.get()==1:
  v5.set(0)
  v6.set(0)
  v7.set(0)
  v4.set(0)
  v9.set(0)
  v10.set(0)
  v11.set(0)
  v12.set(0)
  v8.set(0)
  v14.set(0)
 elif v14.get()==1:
  v5.set(0)
  v6.set(0)
  v7.set(0)
  v4.set(0)
  v9.set(0)
  v10.set(0)
  v11.set(0)
  v12.set(0)
  v13.set(0)
  v8.set(0)
def test():
 if v1.get()==1:
  v2.set(0)
  v3.set(0)
 elif v2.get()==1:
  v1.set(0)
  v3.set(0)
 elif v3.get()==1:
  v2.set(0)
  v1.set(0)
root=tk.Tk()
root.title('AUTOMOBILE REGISTRATION FORM')
root.geometry('1280x600')
l0=tk.Label(root,text='REGISTRATION INFORMATION',font=("Times New Roman",14))
l0.grid(sticky='n',row=0,column=1,columnspan=2)
l1=tk.Label(root,text='Registration Period(Check One)')
l1.grid(sticky='w',row=1)
v1=IntVar()
v2=IntVar()
v3=IntVar()
cb1=Checkbutton(root,text='One Year', variable=v1,onvalue=1, offvalue=0, command=test)
cb1.grid(sticky='w',row=1,column=1)
cb2=Checkbutton(root,text='Two Years(S2 Discount Applies)', variable=v2,onvalue=1, offvalue=0, command=test)
cb2.grid(sticky='w',row=1,column=2)
cb3=Checkbutton(root,text='Three Years(S3 Discount Applies)', variable=v3,onvalue=1, offvalue=0, command=test)
cb3.grid(sticky='w',row=1,column=3)
lemt=tk.Label(root,text='(not available to vehicles subject to emission testing)',font=("Times New Roman",7))
lemt.grid(row=2,column=3)
lrt=tk.Label(root,text='Registration Type(Check One)')
lrt.grid(sticky='w',row=3)
v4=IntVar()
v5=IntVar()
v6=IntVar()
v7=IntVar()
v8=IntVar()
v9=IntVar()
v10=IntVar()
v11=IntVar()
v12=IntVar()
v13=IntVar()
v14=IntVar()
cb4=Checkbutton(root,text='Original', variable=v4,onvalue=1, offvalue=0, command=test1)
cb4.grid(sticky='w',row=3,column=1)
cb5=Checkbutton(root,text='Renewal', variable=v5,onvalue=1, offvalue=0, command=test1)
cb5.grid(sticky='w',row=3,column=2)
cb6=Checkbutton(root,text='Private', variable=v6,onvalue=1, offvalue=0, command=test1)
cb6.grid(sticky='w',row=3,column=3)
cb7=Checkbutton(root,text='Reissue(Plates & Decals)', variable=v7,onvalue=1, offvalue=0, command=test1)
cb7.grid(sticky='w',row=3,column=4)
cb8=Checkbutton(root,text='Reissue(Decals Only)', variable=v8,onvalue=1, offvalue=0, command=test1)
cb8.grid(sticky='w',row=4,column=0)
cb9=Checkbutton(root,text='Rental Vehicle', variable=v9,onvalue=1, offvalue=0, command=test1)
cb9.grid(sticky='w',row=4,column=1)
cb10=Checkbutton(root,text='Transfer Licence Plate Number', variable=v10,onvalue=1, offvalue=0, command=test1)
cb10.grid(sticky='w',row=4,column=2)
tltsv=StringVar()
tltsv.set("Enter Plate NUM")
tlt=tk.Entry(root,textvariable=tltsv,width=15)
tlt.grid(sticky='w',row=4,column=3)
lreis=tk.Label(root,text='See reissue Plates below under plates information.',font=("Times New Roman",5))
lreis.grid(row=4,column=4)
cb11=Checkbutton(root,text='For Hire(complete "For Hire Information section")', variable=v11,onvalue=1, offvalue=0, command=test1)
cb11.grid(sticky='w',row=5,column=0)
cb12=Checkbutton(root,text='Ridesharing(Vanpool)(Cannot exceed 16 passengers including driver)', variable=v12,onvalue=1, offvalue=0, command=test1)
cb12.grid(sticky='w',row=5,column=1)
tltsv1=StringVar()
tltsv1.set("Seating Capacity")
tlt1=tk.Entry(root,textvariable=tltsv1,width=15)
tlt1.grid(sticky='w',row=5,column=2)
cb13=Checkbutton(root,text='Amateur Radio Operator Call Letters - ', variable=v13,onvalue=1, offvalue=0, command=test1)
cb13.grid(sticky='w',row=6,column=0)
tltsv2=StringVar()
tltsv2.set("Specify Letters")
tlt2=tk.Entry(root,textvariable=tltsv2,width=15)
tlt2.grid(sticky='w',row=6,column=1)
cb14=Checkbutton(root,text='Other', variable=v14,onvalue=1, offvalue=0, command=test1)
cb14.grid(sticky='w',row=6,column=2)
tltsv3=StringVar()
tltsv3.set("Specify")
tlt3=tk.Entry(root,textvariable=tltsv3,width=15)
tlt3.grid(sticky='w',row=6,column=3)
loinfo=tk.Label(root,text='OWNER INFORMATION',font=("Times New Roman",14))
loinfo.grid(row=7,column=1,columnspan=2)
lownname=tk.Label(root,text='OWNERS FULL LEGAL NAME OR BUSINESS NAME')
lownname.grid(sticky='w',row=8)
ltele=tk.Label(root,text='TELEPHONE NUMBER')
ltele.grid(sticky='w',row=8,column=1)
ltele1=tk.Label(root,text='CMV CUSTOMER NUMBER/FEIN/SSN')
ltele1.grid(sticky='w',row=8,column=2)
tltsv3_1=StringVar()
tltsv3_1.set("(last,first,mi,suffix)(If business Owned)")
tlt3_1=tk.Entry(root,textvariable=tltsv3_1,width=35)
tlt3_1.grid(sticky='w',row=9,column=0)
tltsv3_2=StringVar()
tltsv3_2.set("(    )")
tlt3_2=tk.Entry(root,textvariable=tltsv3_2,width=10)
tlt3_2.grid(sticky='w',row=9,column=1)
tlt3_3=tk.Entry(root,width=25)
tlt3_3.grid(sticky='w',row=9,column=2)
lownname1=tk.Label(root,text='CO-OWNERS FULL LEGAL NAME')
lownname1.grid(sticky='w',row=10)
ltele1=tk.Label(root,text='TELEPHONE NUMBER')
ltele1.grid(sticky='w',row=10,column=1)
ltele11=tk.Label(root,text='CMV CUSTOMER NUMBER/FEIN/SSN')
ltele11.grid(sticky='w',row=10,column=2)
tltsv31_1=StringVar()
tltsv31_1.set("(last,first,mi,suffix)")
tlt3_11=tk.Entry(root,textvariable=tltsv31_1,width=30)
tlt3_11.grid(sticky='w',row=11,column=0)
tltsv31_2=StringVar()
tltsv31_2.set("(    )")
tlt3_21=tk.Entry(root,textvariable=tltsv31_2,width=10)
tlt3_21.grid(sticky='w',row=11,column=1)
tlt3_31=tk.Entry(root,width=25)
tlt3_31.grid(sticky='w',row=11,column=2)
lnote=tk.Label(root,text='Owners(and Leasers if applicable) Must provide their residence/house/business address where required, this address',font=("Times New Roman",7))
lnote.grid(sticky='w',row=12,columnspan=4)
lnote1=tk.Label(root,text='can not be a P.O. Box. You must complete form ISO-01 if you would like your adress(es) updated.',font=("Times New Roman",7))
lnote1.grid(sticky='w',row=13,columnspan=4)
lres=tk.Label(root,text='RESIDENCE/BUSINESS JURISDICTION')
lres.grid(sticky='w',row=12,column=2)
tres=tk.Entry(root)
tres.grid(sticky='w',row=13,column=2)
ladsv=StringVar()
ladsv.set('Apl # if applicable')
lad=tk.Label(root,text='OWNERS RESIDENCE/BUSINESS ADDRESS')
lad.grid(sticky='w',row=14)
lad1=tk.Label(root,text='CO-OWNERS RESIDENCE/BUSINESS ADDRESS')
lad1.grid(sticky='w',row=16)
tad=tk.Entry(root,textvariable=ladsv,width=30)
tad.grid(sticky='w',row=15)
tad1=tk.Entry(root,textvariable=ladsv,width=30)
tad1.grid(sticky='w',row=17)
lcity=tk.Label(root,text='CITY')
lstate=tk.Label(root,text='STATE')
lzipcode=tk.Label(root,text='ZIP CODE')
lcity.grid(sticky='w',row=14,column=1)
lstate.grid(sticky='w',row=14,column=2)
lzipcode.grid(sticky='w',row=14,column=3)
lcity1=tk.Label(root,text='CITY')
lstate1=tk.Label(root,text='STATE')
lzipcode1=tk.Label(root,text='ZIP CODE')
lcity1.grid(sticky='w',row=16,column=1)
lstate1.grid(sticky='w',row=16,column=2)
lzipcode1.grid(sticky='w',row=16,column=3)
tc=tk.Entry(root)
ts=tk.Entry(root,width=10)
tzc=tk.Entry(root,width=15)
tc.grid(sticky='w',row=15,column=1)
ts.grid(sticky='w',row=15,column=2)
tzc.grid(sticky='w',row=15,column=3)
tc1=tk.Entry(root)
ts1=tk.Entry(root,width=10)
tzc1=tk.Entry(root,width=15)
tc1.grid(sticky='w',row=17,column=1)
ts1.grid(sticky='w',row=17,column=2)
tzc1.grid(sticky='w',row=17,column=3)
lemailadd=tk.Label(root,text='OWNER EMAIL ADDRESS')
lemailadd.grid(sticky='w',row=18)
lemailadd1=tk.Label(root,text='CO-OWNER EMAIL ADDRESS')
lemailadd1.grid(sticky='w',row=18,column=1)
temailadd=tk.Entry(root,width=30)
temailadd.grid(sticky='w',row=19,column=0)
temailadd1=tk.Entry(root,width=30)
temailadd1.grid(sticky='w',row=19,column=1)
laddinfo=tk.Label(root,text='ADDITIONAL INFORMATION',font=("Times New Roman",14))
laddinfo.grid(row=20,column=1,columnspan=2)
lloc=tk.Label(root,text='LOCATION WHERE VEHICLE IS PRINCIPALLY GARAGED',font=("Times New Roman",7))
lloc.grid(sticky='w',row=21,columnspan=2)
vloc1=IntVar()
vloc2=IntVar()
vloc3=IntVar()
cbloc1=tk.Checkbutton(root,text='CITY',variable=vloc1,onvalue=1, offvalue=0, command=test2)
cbloc2=tk.Checkbutton(root,text='COUNTRY',variable=vloc2,onvalue=1, offvalue=0, command=test2)
cbloc3=tk.Checkbutton(root,text='TOWN OF',variable=vloc3,onvalue=1, offvalue=0, command=test2)
cbloc1.grid(sticky='w',row=22,column=0)
cbloc2.grid(sticky='w',row=22,column=1)
cbloc3.grid(sticky='w',row=22,column=2)
tbloc=tk.Entry(root)
tbloc.grid(sticky='w',row=22,column=3)
ldc=tk.Label(root,text='IF NEW LOCATION ENTER DATE CHANGED',font=("Times New Roman",6))
ldc.grid(sticky='w',row=21,column=4)
tdc=tk.Entry(root)
tdc.grid(sticky='w',row=22,column=4)
linfo=tk.Label(root,text='Are any of the owners/leesses on active  military duty or service?')
linfo.grid(sticky='w',row=23,columnspan=2)
vloc21=IntVar()
vloc22=IntVar()
cbloc21=tk.Checkbutton(root,text='YES',variable=vloc21,onvalue=1, offvalue=0, command=f)
cbloc22=tk.Checkbutton(root,text='NO',variable=vloc22,onvalue=1, offvalue=0, command=f)
cbloc21.grid(sticky='w',row=23,column=2)
cbloc22.grid(sticky='w',row=23,column=3)
llike=tk.Label(root,text='IF YOU WOULD LIKE YOUR REGISTRATION RENEWALS SENT TO AN ADDRESS OTHER THAN YOUR RESIDENCE/BUSINESS ADDRESS, ENTER IT BELOW.')
llike.grid(sticky='w',row=24,columnspan=3)
llike1=tk.Label(root,text='REGISTRATION MAILING ADDRESS-OPTIONAL')
llike1.grid(sticky='w',row=25)
tmail=tk.Entry(root,width=20)
tmail.grid(sticky='w',row=26,column=0)
lcity11=tk.Label(root,text='CITY')
lstate11=tk.Label(root,text='STATE')
lzipcode11=tk.Label(root,text='ZIP CODE')
lcity11.grid(sticky='w',row=25,column=1)
lstate11.grid(sticky='w',row=25,column=2)
lzipcode11.grid(sticky='w',row=25,column=3)
tc11=tk.Entry(root)
ts11=tk.Entry(root,width=10)
tzc11=tk.Entry(root,width=15)
tc11.grid(sticky='w',row=26,column=1)
ts11.grid(sticky='w',row=26,column=2)
tzc11.grid(sticky='w',row=26,column=3)
root.mainloop()