import tkinter as tk
from tkinter import *
def f():
    if(v1.get()==1):
        v2.set(0)
    elif(v2.get()==1):
        v1.set(0)
def f2():
    if(v7.get()==1):
        v8.set(0)
    elif(v8.get()==1):
        v7.set(0)
def f1():
    if(v3.get()==1):
        v4.set(0)
        v5.set(0)
        v6.set(0)
    elif(v4.get()==1):
        v3.set(0)
        v5.set(0)
        v6.set(0)
    elif(v5.get()==1):
        v4.set(0)
        v3.set(0)
        v6.set(0)
    elif(v6.get()==1):
        v4.set(0)
        v5.set(0)
        v3.set(0)
root=tk.Tk()
root.title('Hotel Room Accommodation')
root.geometry('900x700')
l1=tk.Label(root,text='Title')
l1.grid(sticky='w',row=0)
t1=tk.Entry(root,width=30)
t1.grid(sticky='w',row=0,column=1)
l2=tk.Label(root,text='Last Name')
l2.grid(sticky='w',row=1)
l3=tk.Label(root,text='First Name(s)')
l3.grid(sticky='w',row=2)
l4=tk.Label(root,text='Share with')
l4.grid(sticky='w',row=3)
l5=tk.Label(root,text='Business Number')
l5.grid(sticky='w',row=4)
l6=tk.Label(root,text='Mobile Number')
l6.grid(sticky='w',row=5)
l7=tk.Label(root,text='Email Address')
l7.grid(sticky='w',row=6)
l8=tk.Label(root,text='Date of Arrival')
l8.grid(sticky='w',row=7)
l9=tk.Label(root,text='Date of Departure')
l9.grid(sticky='w',row=8)
l10=tk.Label(root,text='Name on Credit Card')
l10.grid(sticky='w',row=9)
l11=tk.Label(root,text='Credit  Card Number')
l11.grid(sticky='w',row=10)
l12=tk.Label(root,text='Expiry Date')
l12.grid(sticky='w',row=11)
l13=tk.Label(root,text='CVV Number')
l13.grid(sticky='w',row=12)
l14=tk.Label(root,text='Payment Method')
l14.grid(sticky='w',row=13)
t2=tk.Entry(root,width=30)
t2.grid(sticky='w',row=1,column=1)
t3=tk.Entry(root,width=30)
t3.grid(sticky='w',row=2,column=1)
t4=tk.Entry(root,width=30)
t4.grid(sticky='w',row=3,column=1)
t5=tk.Entry(root,width=30)
t5.grid(sticky='w',row=4,column=1)
t6=tk.Entry(root,width=30)
t6.grid(sticky='w',row=5,column=1)
t7=tk.Entry(root,width=30)
t7.grid(sticky='w',row=6,column=1)
t8=tk.Entry(root,width=30)
t8.grid(sticky='w',row=7,column=1)
t9=tk.Entry(root,width=30)
t9.grid(sticky='w',row=8,column=1)
t10=tk.Entry(root,width=30)
t10.grid(sticky='w',row=9,column=1)
t11=tk.Entry(root,width=30)
t11.grid(sticky='w',row=10,column=1)
t12=tk.Entry(root,width=30)
t12.grid(sticky='w',row=11,column=1)
t13=tk.Entry(root,width=30)
t13.grid(sticky='w',row=12,column=1)
v1=IntVar()
v2=IntVar()
cb1=tk.Checkbutton(root,text='Credit Card', variable=v1,onvalue=1, offvalue=0, command=f)
cb2=tk.Checkbutton(root,text='Direct Bank Transfer', variable=v2,onvalue=1, offvalue=0, command=f)
cb1.grid(sticky='w',row=13,column=1)
cb2.grid(sticky='w',row=13,column=2)
l15=tk.Label(root,text='Negotiated Rates:')
l15.grid(sticky='w',row=14)
v3=IntVar()
v4=IntVar()
cb3=tk.Checkbutton(root,text='Deluxe Room Single- Rs 1700', variable=v3,onvalue=1, offvalue=0, command=f1)
cb4=tk.Checkbutton(root,text='Deluxe Room Double- Rs 1700', variable=v4,onvalue=1, offvalue=0, command=f1)
cb3.grid(sticky='w',row=15,column=0)
cb4.grid(sticky='w',row=15,column=1)
v5=IntVar()
v6=IntVar()
cb5=tk.Checkbutton(root,text='Suites Room Single- Rs 1700', variable=v5,onvalue=1, offvalue=0, command=f1)
cb6=tk.Checkbutton(root,text='Suites Room Double- Rs 1700', variable=v6,onvalue=1, offvalue=0, command=f1)
cb5.grid(sticky='w',row=16,column=0)
cb6.grid(sticky='w',row=16,column=1)
l16=tk.Label(root,text='Room Preference:')
l16.grid(sticky='w',row=17)
v7=IntVar()
v8=IntVar()
cb7=tk.Checkbutton(root,text='King Bed', variable=v7,onvalue=1, offvalue=0, command=f2)
cb8=tk.Checkbutton(root,text='Twin - Two Single Beds', variable=v8,onvalue=1, offvalue=0, command=f2)
cb7.grid(sticky='w',row=18,column=0)
cb8.grid(sticky='w',row=18,column=1)
l17=tk.Label(root,text='The above rates are quoted per room, per night. The rates include breakfast, 1.4% VAT and Excludes 1% Tourism Levy',font=("Times New Roman",7))
l17.grid(sticky='w',row=19,columnspan=4)
l18=tk.Label(root,text='and a voluntary Rs 10 donation to the Arabela Community Trust that will be levied onto your account.',font=("Times New Roman",7))
l18.grid(sticky='w',row=20,columnspan=4)
l19=tk.Label(root,text='Total amount payable ZAR * Nights = ZAR(T)',font=("Times New Roman",7))
l19.grid(sticky='w',row=21,columnspan=2)
l19=tk.Label(root,text='due to Arabela Hotel and Spa',font=("Times New Roman",7))
l19.grid(sticky='w',row=21,column=5)
tv1=StringVar()
tv2=StringVar()
tv3=StringVar()
tv1.set("ZAR")
tv2.set("*Nights")
tv3.set("=ZAR(T)")
t14=tk.Entry(root,textvariable=tv1)
t14.grid(sticky='w',row=21,column=2)
t15=tk.Entry(root,textvariable=tv2)
t15.grid(sticky='w',row=21,column=3)
t16=tk.Entry(root,textvariable=tv3)
t16.grid(sticky='w',row=21,column=4)
l21=tk.Label(root,text='Credit card will be charged on receipt of this form abd details will also be used to settle all incidentals not settled on',font=("Times New Roman",7))
l21.grid(sticky='w',row=22,columnspan=4)
l22=tk.Label(root,text='departure. A copy of the final folio will be sent to you should there be any unsettled changes.',font=("Times New Roman",7))
l22.grid(sticky='w',row=23,columnspan=4)
l23=tk.Label(root,text='In order to qualify for the above rates, your booking needs to be made on or before',font=("Times New Roman",7))
l23.grid(sticky='w',row=24,columnspan=3)
l24=tk.Label(root,text='15 January,2016',fg='red',font=("Times New Roman",7))
l24.grid(sticky='w',row=24,column=2)
l25=tk.Label(root,text='Terms and conditions can be found on the next page',font=("Times New Roman",7))
l25.grid(sticky='w',row=25,columnspan=2)
l26=tk.Label(root,text='The rate is valid for seven days before and after the conference dates. Check in time is 14:00 and check out time is 11:00',font=("Times New Roman",7))
l26.grid(sticky='w',row=26,columnspan=4)
l27=tk.Label(root,text='By your signature hereto, you are accepting all terms and conditions specified on this form and confirm that all information',font=("Times New Roman",7))
l27.grid(sticky='w',row=27,columnspan=4)
l28=tk.Label(root,text='given is current and accurate.',font=("Times New Roman",7))
l28.grid(sticky='w',row=28,columnspan=4)
l28=tk.Label(root,text='Signature')
l28.grid(sticky='w',row=29)
l28=tk.Label(root,text='Print Name:')
l28.grid(sticky='w',row=29,column=2)
l28=tk.Label(root,text='Date')
l28.grid(sticky='w',row=30)
t17=tk.Entry(root,width=30)
t17.grid(sticky='w',row=29,column=1)
t18=tk.Entry(root,width=30)
t18.grid(sticky='w',row=29,column=3)
t19=tk.Entry(root,width=30)
t19.grid(sticky='w',row=30,column=1)
root.mainloop()