import tkinter as tk
from tkinter import *
def f():
    if(v1.get()==1):
        v2.set(0)
        v3.set(0)
        v4.set(0)
    elif(v2.get()==1):
        v1.set(0)
        v3.set(0)
        v4.set(0)
    elif (v3.get() == 1):
        v1.set(0)
        v2.set(0)
        v4.set(0)
    elif (v4.get() == 1):
        v1.set(0)
        v3.set(0)
        v2.set(0)
root=tk.Tk()
root.title('CAR RENTAL RECEIPT')
root.geometry('900x700')
l1=tk.Label(root,text='Date:')
l1.grid(sticky='w',row=0)
l2=tk.Label(root,text='Receipt #:')
l2.grid(sticky='w',row=1)
l3=tk.Label(root,text='Rental Company Info',font=("Times New Roman",12))
l3.grid(sticky='w',row=2,column=1)
l4=tk.Label(root,text='Lessee Info',font=("Times New Roman",12))
l4.grid(sticky='w',row=2,column=3)
l5=tk.Label(root,text='Company:')
l5.grid(sticky='w',row=3)
l6=tk.Label(root,text='Representative:')
l6.grid(sticky='w',row=4)
l7=tk.Label(root,text='Location:')
l7.grid(sticky='w',row=5)
l8=tk.Label(root,text='City/State ZIP:')
l8.grid(sticky='w',row=6)
l9=tk.Label(root,text='Phone:')
l9.grid(sticky='w',row=7)
l10=tk.Label(root,text='Name:')
l10.grid(sticky='w',row=3,column=2)
l11=tk.Label(root,text='Licence#:')
l11.grid(sticky='w',row=4,column=2)
l12=tk.Label(root,text='Address:')
l12.grid(sticky='w',row=5,column=2)
l13=tk.Label(root,text='City/State ZIP:')
l13.grid(sticky='w',row=6,column=2)
l14=tk.Label(root,text='Phone:')
l14.grid(sticky='w',row=7,column=2)
l15=tk.Label(root,text='VEHICLE INFORMATION',font=("Times New Roman",14))
l15.grid(sticky='w',row=8,column=1,columnspan=4)
l16=tk.Label(root,text='VIN:')
l16.grid(sticky='w',row=9)
l17=tk.Label(root,text='Make:')
l17.grid(sticky='w',row=10)
l18=tk.Label(root,text='Year:')
l18.grid(sticky='w',row=11)
l19=tk.Label(root,text='Color:')
l19.grid(sticky='w',row=12)
l20=tk.Label(root,text='Registration#:')
l20.grid(sticky='w',row=9,column=2)
l21=tk.Label(root,text='Model:')
l21.grid(sticky='w',row=10,column=2)
l22=tk.Label(root,text='Mileage:')
l22.grid(sticky='w',row=11,column=2)
t1=tk.Entry(root,width=30)
t1.grid(sticky='w',row=0,column=1)
t2=tk.Entry(root,width=30)
t2.grid(sticky='w',row=1,column=1)
t3=tk.Entry(root,width=30)
t3.grid(sticky='w',row=4,column=1)
t4=tk.Entry(root,width=30)
t4.grid(sticky='w',row=5,column=1)
t5=tk.Entry(root,width=30)
t5.grid(sticky='w',row=6,column=1)
t6=tk.Entry(root,width=30)
t6.grid(sticky='w',row=7,column=1)
t7=tk.Entry(root,width=30)
t7.grid(sticky='w',row=3,column=1)
t8=tk.Entry(root,width=30)
t8.grid(sticky='w',row=4,column=3)
t9=tk.Entry(root,width=30)
t9.grid(sticky='w',row=5,column=3)
t10=tk.Entry(root,width=30)
t10.grid(sticky='w',row=6,column=3)
t11=tk.Entry(root,width=30)
t11.grid(sticky='w',row=7,column=3)
t12=tk.Entry(root,width=30)
t12.grid(sticky='w',row=3,column=3)
t13=tk.Entry(root,width=30)
t13.grid(sticky='w',row=10,column=1)
t14=tk.Entry(root,width=30)
t14.grid(sticky='w',row=11,column=1)
t15=tk.Entry(root,width=30)
t15.grid(sticky='w',row=12,column=1)
t16=tk.Entry(root,width=30)
t16.grid(sticky='w',row=9,column=1)
t17=tk.Entry(root,width=30)
t17.grid(sticky='w',row=10,column=3)
t18=tk.Entry(root,width=30)
t18.grid(sticky='w',row=11,column=3)
t19=tk.Entry(root,width=30)
t19.grid(sticky='w',row=9,column=3)
l23=tk.Label(root,text='VIN')
l23.grid(sticky='w',row=13)
l24=tk.Label(root,text='Cost/Day')
l24.grid(sticky='w',row=13,column=1)
l25=tk.Label(root,text='# of Days')
l25.grid(sticky='w',row=13,column=2)
l26=tk.Label(root,text='Additional Costs')
l26.grid(sticky='w',row=13,column=3)
l27=tk.Label(root,text='Line Total')
l27.grid(sticky='w',row=13,column=4)
t191=tk.Entry(root)
t191.grid(sticky='w',row=14,column=0)
t20=tk.Entry(root)
t20.grid(sticky='w',row=15,column=0)
t21=tk.Entry(root)
t21.grid(sticky='w',row=16,column=0)
t22=tk.Entry(root,width=10)
t22.grid(sticky='w',row=14,column=1)
t23=tk.Entry(root,width=10)
t23.grid(sticky='w',row=15,column=1)
t24=tk.Entry(root,width=10)
t24.grid(sticky='w',row=16,column=1)
t25=tk.Entry(root)
t25.grid(sticky='w',row=14,column=2)
t26=tk.Entry(root)
t26.grid(sticky='w',row=15,column=2)
t27=tk.Entry(root)
t27.grid(sticky='w',row=16,column=2)
t28=tk.Entry(root,width=20)
t28.grid(sticky='w',row=14,column=3)
t29=tk.Entry(root,width=20)
t29.grid(sticky='w',row=15,column=3)
t30=tk.Entry(root,width=20)
t30.grid(sticky='w',row=16,column=3)
t31=tk.Entry(root)
t31.grid(sticky='w',row=14,column=4)
t32=tk.Entry(root)
t32.grid(sticky='w',row=15,column=4)
t33=tk.Entry(root)
t33.grid(sticky='w',row=16,column=4)
l28=tk.Label(root,text='Payment Method:')
l28.grid(sticky='w',row=17)
v1=IntVar()
v2=IntVar()
v3=IntVar()
v4=IntVar()
cb1=tk.Checkbutton(root,text='Cash', variable=v1,onvalue=1, offvalue=0, command=f)
cb2=tk.Checkbutton(root,text='Check', variable=v2,onvalue=1, offvalue=0, command=f)
cb3=tk.Checkbutton(root,text='Credit', variable=v3,onvalue=1, offvalue=0, command=f)
cb4=tk.Checkbutton(root,text='Other', variable=v4,onvalue=1, offvalue=0, command=f)
cb1.grid(sticky='w',row=18)
cb2.grid(sticky='w',row=18,column=1)
cb3.grid(sticky='w',row=19)
cb4.grid(sticky='w',row=20)
cqno=StringVar()
crno=StringVar()
cqno.set("Check No.")
crno.set("Credit No.")
t34=tk.Entry(root,textvariable=cqno)
t34.grid(sticky='w',row=18,column=2)
t35=tk.Entry(root,textvariable=crno)
t35.grid(sticky='w',row=19,column=1)
t36=tk.Entry(root)
t36.grid(sticky='w',row=20,column=1)
l29=tk.Label(root,text='Subtotal:')
l29.grid(sticky='w',row=17,column=3)
l30=tk.Label(root,text='Tax(12.5%):')
l30.grid(sticky='w',row=18,column=3)
l31=tk.Label(root,text='Total:')
l31.grid(sticky='w',row=19,column=3)
l32=tk.Label(root,text='Amount Paid:')
l32.grid(sticky='w',row=20,column=3)
l33=tk.Label(root,text='Authorized Signature:',font=("Times New Roman",12))
l33.grid(sticky='e',row=21,column=3)
l34=tk.Label(root,text='Representative Name:')
l34.grid(sticky='e',row=22,column=3)
t37=tk.Entry(root)
t37.grid(sticky='w',row=17,column=4)
t38=tk.Entry(root)
t38.grid(sticky='w',row=18,column=4)
t39=tk.Entry(root)
t39.grid(sticky='w',row=19,column=4)
t40=tk.Entry(root)
t40.grid(sticky='w',row=20,column=4)
t41=tk.Entry(root,width=30)
t41.grid(sticky='e',row=21,column=4)
t42=tk.Entry(root,width=30)
t42.grid(sticky='e',row=22,column=4)
root.mainloop()