import tkinter as tk
from tkinter import *
from tkinter import  messagebox
def fb():
    msg = messagebox.showinfo("Balance", "Balance=Total Loan Amount- Amount Paid")
def mp():
    msg = messagebox.showinfo("Monthly Payment", "Monthly Payment= Remaining loan amount*(Interest rate)")
root=tk.Tk()
root.title('tk')
root.geometry('400x200')
l1=tk.Label(root,text="Annual Rate:")
l1.grid(sticky='w',row=0,column=0)
t1=tk.Entry(root)
t1.grid(sticky='w',row=0,column=1)
l2=tk.Label(root,text="Number of payments:")
l2.grid(sticky='w',row=1,column=0)
t2=tk.Entry(root)
t2.grid(sticky='w',row=1,column=1)
v = StringVar(root)
l3=tk.Label(root,text="Loan Principle:")
l3.grid(sticky='w',row=2,column=0)
t3=tk.Entry(root)
t3.grid(sticky='w',row=2,column=1)
l4=tk.Label(root,text="Monthly Payment:")
l4.grid(sticky='w',row=3,column=0)
t4=tk.Entry(root)
t4.grid(sticky='w',row=3,column=1)
l5=tk.Label(root,text="Remaining Loan:")
l5.grid(sticky='w',row=4,column=0)
t5=tk.Entry(root)
t5.grid(sticky='w',row=4,column=1)
b1=tk.Button(root, text='Find Balance',command=fb)
b1.grid(sticky='w',row=5,column=0)
b2=tk.Button(root, text='Monthly Payment',command=mp)
b2.grid(sticky='w',row=5,column=1)
b3=tk.Button(root, text='Quit',command=root.destroy)
b3.grid(sticky='w',row=5,column=2)
root.mainloop()