import tkinter as tk
from tkinter import *
from tkinter import  messagebox
def fb():
    msg = messagebox.showinfo("Contact Displaying", "In Development")
def mp():
    msg = messagebox.showinfo("Contact Addition","Contact Added")
def s():
    msg = messagebox.showinfo("Search Query","In Development")
root=tk.Tk()
root.title('tk')
root.geometry('370x350')
l12=tk.Label(root,text='Contact List')
l12.grid(row=0,column=0)
t12=tk.Entry(root)
t12.grid(row=1)
l11=tk.Label(root,text="New Contact")
l11.grid(row=0,column=2)
l1=tk.Label(root,text="First Name:")
l1.grid(sticky='e',row=1,column=1)
t1=tk.Entry(root)
t1.grid(sticky='e',row=1,column=2)
l2=tk.Label(root,text="Last Name:")
l2.grid(sticky='e',row=2,column=1)
t2=tk.Entry(root)
t2.grid(sticky='e',row=2,column=2)
v = StringVar(root)
l3=tk.Label(root,text="Loan Principle:")
l3.grid(sticky='e',row=3,column=1)
t3=tk.Entry(root)
t3.grid(sticky='e',row=3,column=2)
l4=tk.Label(root,text="Phone #:")
l4.grid(sticky='e',row=4,column=1)
t4=tk.Entry(root)
t4.grid(sticky='e',row=4,column=2)
v1=IntVar()
cb1=Checkbutton(root,text='Friend', variable=v1,onvalue=1, offvalue=0)
cb1.grid(row=5,column=2)
l5=tk.Label(root,text="Email:")
l5.grid(sticky='e',row=6,column=1)
t5=tk.Entry(root)
t5.grid(sticky='w',row=6,column=2)
l7=tk.Label(root,text="Birthday:")
l7.grid(sticky='e',row=7,column=1)
t7=tk.Entry(root)
t7.grid(sticky='w',row=7,column=2)
l6=tk.Label(root,text="Last Name")
l6.grid(sticky='w',row=10,column=0)
t6=tk.Entry(root)
t6.grid(sticky='w',row=10,column=1)
b1=tk.Button(root, text='Display Contact',command=fb)
b1.grid(sticky='w',row=9,column=0)
b2=tk.Button(root, text='Search',command=s)
b2.grid(sticky='w',row=11,column=1)
b3=tk.Button(root, text='Add Contact',command=mp)
b3.grid(sticky='e',row=8,column=2)
root.mainloop()