import tkinter as tk
from tkinter import *
from tkinter import  messagebox
def hello1():
 msg = messagebox.showinfo( "Confirmation","Submitted Sucessfully")
root=tk.Tk()
root.title('tk')
root.geometry('350x200')
root.configure(bg='light green')
l1=tk.Label(root,text="Name",bg='light green')
l1.grid(row=0)
t1=tk.Entry(root,width=40)
t1.grid(row=0,column=1)
l2=tk.Label(root,text="Course",bg='light green')
l2.grid(row=1)
t2=tk.Entry(root,width=40)
t2.grid(row=1,column=1)
l3=tk.Label(root,text="Semester",bg='light green')
l3.grid(row=2)
t3=tk.Entry(root,width=40)
t3.grid(row=2,column=1)
l4=tk.Label(root,text="Form No.",bg='light green')
l4.grid(row=3)
t4=tk.Entry(root,width=40)
t4.grid(row=3,column=1)
l5=tk.Label(root,text="Contact No.",bg='light green')
l5.grid(row=4)
t5=tk.Entry(root,width=40)
t5.grid(row=4,column=1)
l6=tk.Label(root,text="Email id",bg='light green')
l6.grid(row=5)
t6=tk.Entry(root,width=40)
t6.grid(row=5,column=1)
l7=tk.Label(root,text="Address",bg='light green')
l7.grid(row=6)
t7=tk.Entry(root,width=40)
t7.grid(row=6,column=1)
b1=tk.Button(root, text='Sumbit',fg='dark blue',bg='red',command=hello1)
b1.grid(sticky='s',row=7,column=1)
root.mainloop()
