from tkinter import *
def f():

    l1.config(text=stringvar.get())
root=Tk()
root.geometry('500x500')
root.title('CT2')
l1=Label(root,text="Hello There")
stringvar=StringVar(root,value="This")
e1=Entry(root,textvariable=stringvar)
s1=Spinbox(root,from_=1,to=5)
l1.grid()
e1.grid()
s1.grid(column=3)
b1=Button(root,text='Quit',command=root.destroy)
b1.grid()
var1=IntVar()
var2=IntVar()
cb1=Checkbutton(root,text="Textofcheckbutton",variable=var1,onvalue=1,offvalue=0)
rb1=Radiobutton(root,text="Textofradiobutton",variable=var2,value=5)
cb1.grid()
rb1.grid()
spin1=Scale(root,from_=10,to=50,orient=HORIZONTAL)
spin1.grid()
variablex=IntVar()
d=OptionMenu(root,variablex,"1","2","3","4","Five")
d.grid()
b2=Button(root,text='Update!',command=f)
b2.grid()
root.mainloop()