import sqlite3
root=sqlite3.connect('COURSE.db')
root.execute('''CREATE TABLE IF NOT EXISTS PRODUCT(ID  INT PRIMARY KEY,PROD_NAME TEXT,SUPPLIER_ID INT,UNIT_PRICE REAL,PACKAGE TEXT,ORDER_ID INT);''')
root.execute('''CREATE TABLE IF NOT EXISTS ORDERITEM(ID INT,ORDER_ID INT PRIMARY KEY,PRODUCT_ID INT,UNIT_PRICE REAL,QUANTITY INT,CONSTRAINT fk_PRODUCT FOREIGN KEY (ID)  REFERENCES PRODUCT(ID));''')
root.execute("INSERT INTO PRODUCT (ID,PROD_NAME,SUPPLIER_ID,UNIT_PRICE,PACKAGE,ORDER_ID) \
      VALUES (1,'BAT',11,45.99,'AMAZON',111);")
root.execute("INSERT INTO PRODUCT (ID,PROD_NAME,SUPPLIER_ID,UNIT_PRICE,PACKAGE,ORDER_ID) \
      VALUES (2,'BALL',12,465.99,'FLIPKART',212);")
root.execute("INSERT INTO ORDERITEM (ID,ORDER_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY) \
      VALUES (1,111,777,45.99,2);")
root.execute("INSERT INTO ORDERITEM (ID,ORDER_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY) \
      VALUES (2,212,888,465.99,1);")
root.commit()
root.execute('SELECT SUM(QUANTITY) FROM ORDERITEM;')
root.execute('SELECT UNIT_PRICE FROM PRODUCT ORDER BY SUPPLIER_ID;')
root.execute('SELECT PROD_NAME,ORDER_ID,SUPPLIER_ID FROM PRODUCT;')
root.close()