import sqlite3
root=sqlite3.connect('Ques4.db')
root.execute('''CREATE TABLE IF NOT EXISTS JOB(JOB_ID INT PRIMARY KEY,JOB_TITLE TEXT,MIN_SALARY REAL,MAX_SALARY REAL);''')
root.execute("INSERT INTO JOB(JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY)\
    VALUES(1,'GM',75000.99,150000.45);")
root.execute("INSERT INTO JOB(JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY)\
    VALUES(2,'HR',65000.99,100000.45);")
root.execute("INSERT INTO JOB(JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY)\
    VALUES(3,'D',95000.99,250000.45);")
root.execute("INSERT INTO JOB(JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY)\
    VALUES(4,'PEON',750.99,1500.45);")
root.commit()
root.close()