import tkinter as tk
from tkinter import *
from tkinter import messagebox
import sqlite3
root=tk.Tk()
root.title('tk')
root.geometry('300x200')
Fullname=StringVar()
Email=StringVar()
v=StringVar()
var1=IntVar()
def fdb():
    name1 = Fullname.get()
    email = Email.get()
    gender = radio1.get()
    country = v.get()
    prog = var1.get()
    conn = sqlite3.connect('Ques4.db')
    conn.execute('''CREATE TABLE IF NOT EXISTS STU_DATA(REG_NO TEXT PRIMARY KEY,NAME TEXT,DEPT TEXT,GENDER TEXT,AGE INT);''')
    conn.execute('INSERT INTO STU_DATA(REG_NO,NAME,DEPT,GENDER,AGE) VALUES(?,?,?,?,?)',
                       (name1, email,country, gender,prog,))
    conn.commit()
    msg = messagebox.showinfo("Confirmation", "Inserted Sucessfully")
def hello2():
 msg = messagebox.showinfo( "Confirmation","Updated Sucessfully")

l1=tk.Label(root,text="Regno")
l1.grid(row=0)
t1=tk.Entry(root, textvar=Fullname)
t1.grid(row=0,column=1)
l2=tk.Label(root,text="Name:")
l2.grid(row=1)
t2=tk.Entry(root, textvar=Email)
t2.grid(row=1,column=1)
v = StringVar(root, value='CSE')
l3=tk.Label(root,text="Dept")
l3.grid(row=2)
t3=tk.Entry(root,textvariable=v)
t3.grid(row=2,column=1)
l4=tk.Label(root,text="Gender")
l4.grid(row=3)
radio1=StringVar()
rb1=Radiobutton(root,text='Male',variable=radio1,value='MALE')
rb1.grid(row=3,column=1)
rb2=Radiobutton(root,text='Female',variable=radio1,value='FEMALE')
rb2.grid(row=3,column=2)
l5=tk.Label(root,text="Age")
l5.grid(row=4)
spin = Spinbox(root,from_=15,to=20,textvariable=var1)
spin.grid(row=4,column=1)
b1=tk.Button(root, text='Insert',command=fdb)
b1.grid(row=5,column=0)
b2=tk.Button(root, text='Update',command=hello2)
b2.grid(row=5,column=1)
b3=tk.Button(root, text='Delete')
b3.grid(row=6,column=0)
b4=tk.Button(root, text='Select')
b4.grid(row=6,column=1)
root.mainloop()